# Generated by Django 5.1.3 on 2024-12-02 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_director_options_alter_genre_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Актер")),
            ],
            options={
                "verbose_name": "Актер",
                "verbose_name_plural": "Актеры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Страна")),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="director",
            options={
                "ordering": ["name"],
                "verbose_name": "Режиссер",
                "verbose_name_plural": "Режиссеры",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["name"],
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанр",
            },
        ),
        migrations.AlterModelOptions(
            name="mediatype",
            options={
                "ordering": ["name"],
                "verbose_name": "Тип медиа",
                "verbose_name_plural": "Типы медиа",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "рецензия",
                "verbose_name_plural": "рецензии",
            },
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.director",
                verbose_name="Режиссер",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="value",
            field=models.IntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
