# Generated by Django 5.1.3 on 2024-12-02 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_actor_country_alter_director_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.actor",
                verbose_name="Актер",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.country",
                verbose_name="Страна",
            ),
        ),
    ]
