# Generated by Django 5.1.3 on 2024-12-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_actor_movie_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="actor",
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True, to="movies.actor", verbose_name="Актеры"
            ),
        ),
    ]
