# Generated by Django 5.1.3 on 2024-12-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_remove_movie_actor_movie_actors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="country",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.AddField(
            model_name="movie",
            name="countries",
            field=models.ManyToManyField(
                blank=True, to="movies.country", verbose_name="Страны"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(
                blank=True, to="movies.director", verbose_name="Режиссер"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(
                blank=True, to="movies.genre", verbose_name="Жанры"
            ),
        ),
    ]
